user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

user_add:
    path:     /home/add
    defaults: { _controller: UserBundle:User:add }

user_edit:
    path:     /user/edit
    defaults: { _controller: UserBundle:User:edit }

contact_add:
    path:     /user/add
    defaults: { _controller: UserBundle:Contact:add }

contact_delete:
    path:     /user/delete
    defaults: { _controller: UserBundle:Contact:delete }

user_account:
    path:     /user/account
    defaults: { _controller: UserBundle:User:account }

user_contacts:
    path:     /user/contacts
    defaults: { _controller: UserBundle:User:contacts }